export const GAME_CATEGORIES = {
  STICKMAN: 'Stickman',
  RUNNER: 'Runner',
  SHOOTING: 'Shooting',
  PUZZLE: 'Puzzle',
  ARCADE: 'Arcade',
  CASUAL: 'Casual',
  RACING: 'Racing',
  STRATEGY: 'Strategy',
  ACTION: 'Action',
};

export const GAMES = [
  {
    id: 'tap-jump',
    slug: 'tap-jump',
    title: 'Tap Jump',
    category: GAME_CATEGORIES.ARCADE,
    description: 'Jump and collect stars to score!',
    thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=500',
    gameUrl: '/games/tap-jump/index.html',
    hasFullGame: true,
    rating: '4.7',
    plays: '156K',
    featured: false,
  },
  {
    id: 'snake',
    slug: 'snake',
    title: 'Snake Classic',
    category: GAME_CATEGORIES.ARCADE,
    description: 'Guide your snake to eat and grow. Avoid walls and yourself!',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=500',
    gameUrl: '/games/snake/index.html',
    hasFullGame: true,
    rating: '4.8',
    plays: '125K',
    featured: true,
  },
  {
    id: 'tic-tac-toe',
    slug: 'tic-tac-toe',
    title: 'Tic Tac Toe AI',
    category: GAME_CATEGORIES.PUZZLE,
    description: 'Challenge the AI in this classic strategy game.',
    thumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=500',
    gameUrl: '/games/tic-tac-toe/index.html',
    hasFullGame: true,
    rating: '4.5',
    plays: '87K',
    featured: true,
  },
  {
    id: 'bubble-pop',
    slug: 'bubble-pop',
    title: 'Bubble Pop',
    category: GAME_CATEGORIES.CASUAL,
    description: 'Pop bubbles before they escape!',
    thumbnail: 'https://images.unsplash.com/photo-1559003926-356ae25a9cb0?auto=format&fit=crop&q=80&w=500',
    gameUrl: '/games/bubble-pop/index.html',
    hasFullGame: true,
    rating: '4.4',
    plays: '112K',
    featured: false,
  },
  {
    id: 'fruit-slice',
    slug: 'fruit-slice',
    title: 'Fruit Slice',
    category: GAME_CATEGORIES.ARCADE,
    description: 'Slice fruits with swift swipes!',
    thumbnail: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&q=80&w=500',
    gameUrl: '/games/fruit-slice/index.html',
    hasFullGame: true,
    rating: '4.6',
    plays: '98K',
    featured: true,
  },
  {
    id: 'quiz-rush',
    slug: 'quiz-rush',
    title: 'Quiz Rush',
    category: GAME_CATEGORIES.PUZZLE,
    description: 'Test your knowledge in this fast-paced quiz!',
    thumbnail: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=500',
    gameUrl: '/games/quiz-rush/index.html',
    hasFullGame: true,
    rating: '4.6',
    plays: '94K',
    featured: false,
  },
  {
    id: 'bubble-shooter',
    slug: 'bubble-shooter',
    title: 'Bubble Shooter',
    category: GAME_CATEGORIES.ARCADE,
    description: 'Match and pop bubbles to clear the board!',
    thumbnail: 'https://images.unsplash.com/photo-1559003926-356ae25a9cb0?auto=format&fit=crop&q=80&w=500',
    gameUrl: '/games/bubble-shooter/index.html',
    hasFullGame: true,
    rating: '4.8',
    plays: '145K',
    featured: true,
  },
  {
    id: 'stickman-runner',
    slug: 'stickman-runner',
    title: 'Stickman Runner',
    category: GAME_CATEGORIES.RUNNER,
    description: 'Run, jump, and slide through endless obstacles!',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=500',
    gameUrl: '/games/stickman-runner/index.html',
    hasFullGame: true,
    rating: '4.6',
    plays: '95K',
    featured: false,
  },
  {
    id: 'zombie-defense',
    slug: 'zombie-defense',
    title: 'Zombie Defense',
    category: GAME_CATEGORIES.SHOOTING,
    description: 'Defend against waves of zombies!',
    thumbnail: 'https://images.unsplash.com/photo-1509248961895-40216abe3d2a?auto=format&fit=crop&q=80&w=500',
    gameUrl: '/games/zombie-defense/index.html',
    hasFullGame: true,
    rating: '4.7',
    plays: '120K',
    featured: false,
  },
  {
    id: 'space-shooter',
    slug: 'space-shooter',
    title: 'Space Shooter',
    category: GAME_CATEGORIES.SHOOTING,
    description: 'Defend the galaxy from alien invasion!',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=500',
    gameUrl: '/games/space-shooter/index.html',
    hasFullGame: true,
    rating: '4.8',
    plays: '150K',
    featured: true,
  },
  {
    id: 'city-runner',
    slug: 'city-runner',
    title: 'City Runner',
    category: GAME_CATEGORIES.RUNNER,
    description: 'Run through the city streets, dodge obstacles and collect coins!',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=500',
    gameUrl: '/games/city-runner/index.html',
    hasFullGame: true,
    rating: '4.8',
    plays: '180K',
    featured: true,
  },
  {
    id: 'stickman-battle',
    slug: 'stickman-battle',
    title: 'Stickman Battle Arena',
    category: GAME_CATEGORIES.ACTION,
    description: 'Fight enemies in an epic battle arena with unlockable weapons!',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=500',
    gameUrl: '/games/stickman-battle/index.html',
    hasFullGame: true,
    rating: '4.9',
    plays: '200K',
    featured: true,
  },
  {
    id: 'zombie-survival',
    slug: 'zombie-survival',
    title: 'Zombie Survival',
    category: GAME_CATEGORIES.SHOOTING,
    description: 'Survive waves of zombies with multiple weapons and powerups!',
    thumbnail: 'https://images.unsplash.com/photo-1509248961895-40216abe3d2a?auto=format&fit=crop&q=80&w=500',
    gameUrl: '/games/zombie-survival/index.html',
    hasFullGame: true,
    rating: '4.8',
    plays: '220K',
    featured: true,
  },
  {
    id: 'sniper-mission',
    slug: 'sniper-mission',
    title: 'Sniper Mission',
    category: GAME_CATEGORIES.SHOOTING,
    description: 'Complete sniper missions with zoom mechanics and precision shooting!',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=500',
    gameUrl: '/games/sniper-mission/index.html',
    hasFullGame: true,
    rating: '4.7',
    plays: '160K',
    featured: false,
  },
  {
    id: 'car-parking',
    slug: 'car-parking',
    title: 'Car Parking Simulator',
    category: GAME_CATEGORIES.RACING,
    description: 'Master parking skills in realistic driving missions with increasing difficulty!',
    thumbnail: '/images/games/car-parking.svg',
    gameUrl: '/games/car-parking/index.html',
    hasFullGame: true,
    rating: '4.8',
    plays: '180K',
    featured: true,
  },
];

export function getGameBySlug(slug) {
  return GAMES.find(game => game.slug === slug) || null;
}

export function getGamesByCategory(category) {
  if (category === 'All Games') return GAMES;
  return GAMES.filter(game => game.category === category);
}

export function getFeaturedGames() {
  return GAMES.filter(game => game.featured);
}

export function getPlayableGames() {
  return GAMES.filter(game => game.hasFullGame);
}

export function getCategories() {
  const uniqueCategories = [...new Set(GAMES.map(game => game.category))];
  return ['All Games', ...uniqueCategories];
}

export const GAME_CONFIG = {
  'tap-jump': { coinsPerWin: 50 },
  'snake': { coinsPerWin: 50 },
  'tic-tac-toe': { coinsPerWin: 30 },
  'bubble-pop': { coinsPerWin: 40 },
  'fruit-slice': { coinsPerWin: 50 },
  'quiz-rush': { coinsPerWin: 60 },
  'bubble-shooter': { coinsPerWin: 60 },
  'stickman-runner': { coinsPerWin: 50 },
  'zombie-defense': { coinsPerWin: 60 },
  'space-shooter': { coinsPerWin: 70 },
  'city-runner': { coinsPerWin: 60 },
  'stickman-battle': { coinsPerWin: 80 },
  'zombie-survival': { coinsPerWin: 70 },
  'sniper-mission': { coinsPerWin: 75 },
  'car-parking': { coinsPerWin: 80 },
};

export function getCoinsForGame(slug) {
  return GAME_CONFIG[slug]?.coinsPerWin || 0;
}